---
title: "Operational Record"
output: html_document
params:
  gVars: NA
  input: NA
  srcDir: NA
always_allow_html: yes
---




<br>
```{r, pt_GLP_report_title, echo=FALSE, results='asis'}
if (!params$gVars$working_status) { #multiple mode and existing issue entries
  h2("case: Integration of multiple curated datasets")

} else {   #single case
  h2("case: Single dataset curation")
  
}
```

```{css, echo=FALSE}
h3 {
   margin-top: -5px;
   text-align: center;
}
```


```{r, glp_or_pt_colnames_and_mode, echo=FALSE} 

if (!params$input$GLP_inactivation_mode) {  
            colnames <-  c("Step ID", "Type of Operation and GLP Comment")
            subtitle_glp_pt <- "mode: GLP"
} else {    #GLP disabled
    colnames <- c("Step ID", "Type of Operation")
    subtitle_glp_pt <- "mode: only procedure"
}

h3(subtitle_glp_pt)

```


## Timestamp 
```{r, echo=FALSE}

print(Sys.time())

```


## Session Unique Identifier
```{r, echo=FALSE}
id <- data.frame(params$gVars$sha256_stringID)
kbl(id, format="html",booktabs = TRUE, align="c",
                col.names = NULL, table.attr = "style = \"color: dodgerblue;\"")  %>% 
                     kable_styling (font_size = 16, bootstrap_options = c("striped", "condensed")) %>%
  column_spec(1, bold=TRUE)


```

<br>

## Procedural Track
```{r,eval=knitr::is_html_output(), echo=FALSE}

if(isTruthy(params$gVars$glp_comment_rep)){
    steps <- (params$gVars$glp_comment_rep)   
  #  knitr::kable(p , "html", escape=FALSE)
    kbl(steps, escape = FALSE, format="html",booktabs = TRUE, align="l", 
        col.names = colnames)   %>% 
                     kable_styling (bootstrap_options = c("striped", "condensed")) #%>%
}
```
