---
title: "Multiple Integration Tool Check - Consistent entries"
output: html_document
params:
  gVars: NA
  input: NA
  srcDir: NA
always_allow_html: yes
---


## Integration of Multiple Curated Datasets

## Timestamp 
```{r, echo=FALSE}

print(Sys.time())

```
<br>


## Session Unique Identifier
```{r, echo=FALSE}
id <- data.frame(params$gVars$sha256_stringID)
kbl(id, format="html",booktabs = TRUE, align="c",
                col.names = NULL, table.attr = "style = \"color: dodgerblue;\"")  %>% 
                     kable_styling (font_size = 16, bootstrap_options = c("striped", "condensed")) %>%
  column_spec(1, bold=TRUE)

```
<br>

## Arbiter(s) evaluating the entries as 'Consistent'
```{r, echo=FALSE , results='asis'}

if (length(params$gVars$multi_ACmsg)>0){
  
      arbiterAC <- purrr::map(params$gVars$multi_ACmsg,2)  %>% as.character(.)%>% unique(.) 
      } else { arbiterAC<-NA}


if (length(params$gVars$multi_ACmsg)>0){
  arbiterAC_kbl <- kbl(arbiterAC, escape = FALSE, format="html", booktabs = TRUE, align=c("l","c"),
                     col.names=NULL, row.names=TRUE) %>%
                    kable_styling(bootstrap_options = c("striped", "condensed")) %>% column_spec(1, width = "30em")
                     
  cat(arbiterAC_kbl) 
  } else {cat("No entries assessed as 'Consistent'")}

```



## List of 'Consistent' entries 

The column names are listed according to the order of acceptance. 
<br>

```{r, echo=FALSE, results= 'asis'}

if (length(params$gVars$multi_ACmsg)>0){
  all_consistent <- as.data.frame(params$gVars$multi_ACmsg) %>% 
                        do.call(rbind.data.frame, .)  %>% setNames(.,c("Consistent Entries", "Arbiter")) #%>%      head(.)
  consistent_kbl <- kbl(all_consistent, escape = FALSE, format="html", booktabs = TRUE, align=c("l","c"),
                     col.names=c("Consistent Entries", "Arbiter"), row.names=TRUE) %>%
                    kable_styling(bootstrap_options = c("striped", "condensed"))
                     
  cat(consistent_kbl) 
  }

```
